### ISSUE TITLE
这个的安装方法

### ISSUE THREAD

**Issue by tonychanczm** [Okabe-Kurisu/sspanel-v3-mod-mod#2]
这个的安装方法请问是不是和g大的一样呢？还有您那个支付宝付款请问是怎么做的呢？
---来自仰望大佬的弱渣的提问

**Comment by Okabe-Kurisu** [comment]
是和G大的一样，支付宝是g大自己写的https://github.com/esdeathlove/ss-panel-v3-mod/issues/418
这样以后在配置文件中会有三行新的配置项，去spay买个服务把key放进去就行了。
不过我这个版本不能用这个方法更新spay支持。。因为他要验证文件信息，修改过的就没办法加入spay功能了。。
