### ISSUE TITLE
大佬，请教个问题。

### ISSUE THREAD

**Issue by malzaher** [Okabe-Kurisu/sspanel-v3-mod-mod#3]
搭建好了，点击邀请好友显示500，您这边好像没有给出sql文件，我导入的是g大的glzjin_all.sql原版的。请问如何解决？

**Comment by Okabe-Kurisu** [comment]
啊啊，是啊，春节弄得太急搞忘了。我刚刚把数据库文件上传上来了，https://github.com/Okabe-Kurisu/sspanel-v3-mod-mod/blob/master/sspanel_1.sql
把这个导入sspanel中就可以了

**Comment by malzaher** [comment]
刚看到，谢谢了，这两天比较忙，过两天试试。
